version: "3.8"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/lost-but-found
      - JWT_SECRET=3469670a2ec6bce338f392dac790a564bfab5239a177f72e7e919df5fefc42b9
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
