name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa stephane@51.38.185.29 << 'EOF'
            cd lost-but-found-backend || exit
            git pull origin main || exit
            docker-compose down || exit
            docker-compose up -d || exit
          EOF
